//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS_General_QCmodule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TS_General_QCmodule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add_14x {
            get {
                object obj = ResourceManager.GetObject("Add_14x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel_12x {
            get {
                object obj = ResourceManager.GetObject("Cancel_12x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CodeClassTranslate&gt;
        ///Type,CodeClass,Analyte,ControlType,ClassActive
        ///dsp,DSP,dsp,,3
        ///ps,Positive,Control,ERCC,3
        ///ps,Negative,Control,ERCC,3
        ///ps,Purification,Control,Hyb_Independent,1
        ///ps,Endogenous1s,mRNA,,2
        ///ps,Housekeeping1s,Control,Housekeeping,2
        ///ps,Endogenous2s,mRNA,,2
        ///ps,Housekeeping2s,Control,Housekeeping,2
        ///ps,Endogenous3s,mRNA,,2
        ///ps,Housekeeping3s,Control,Housekeeping,2
        ///ps,Endogenous4s,mRNA,,2
        ///ps,Housekeeping4s,Control,Housekeeping,2
        ///ps,Endogenous5s,mRNA,,2
        ///ps,Housekeeping5s,Control,Housekee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeClassTranslator {
            get {
                return ResourceManager.GetString("CodeClassTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Key_32x {
            get {
                object obj = ResourceManager.GetObject("Key_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] n6_vRCC16 {
            get {
                object obj = ResourceManager.GetObject("n6_vRCC16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusHelp_16x {
            get {
                object obj = ResourceManager.GetObject("StatusHelp_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusHelp_32x {
            get {
                object obj = ResourceManager.GetObject("StatusHelp_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusInformation_cyan_32x {
            get {
                object obj = ResourceManager.GetObject("StatusInformation_cyan_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
